# Generated by Django 3.2.3 on 2021-06-26 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collectionId', models.UUIDField()),
                ('artist_name', models.CharField(max_length=255)),
                ('art_title', models.TextField(blank=True)),
                ('work_type', models.TextField(blank=True)),
                ('media_type', models.TextField(blank=True)),
                ('support_type', models.TextField(blank=True)),
                ('art_width', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('art_height', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('measure_units', models.TextField(blank=True, default='inches')),
                ('originalImage', models.ImageField(upload_to='original/')),
                ('filelen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('blob_url', models.URLField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
