# Generated by Django 3.2.3 on 2021-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='analytics',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
